name: SEO Optimization
description: 'Tech Blog Collection by Ashok Murugan - Software Engineering Career Growth, Interview Preparation, System Design, and Programming Best Practices'

# Topics for GitHub search and discovery
topics:
  - software-engineering
  - tech-blogs
  - career-development
  - interview-preparation
  - system-design
  - programming-tutorials
  - coding-interview
  - tech-career
  - software-developer
  - engineering-management
  - algorithms
  - data-structures
  - maang-interviews
  - technical-writing
  - developer-resources

# Labels for repository categorization
labels:
  - blog
  - documentation
  - education
  - tutorial
  - career
  - interview
  - programming
